In [23]:

import pandas as pd
df_public = pd.read_csv("survey_results_public.csv")
df1_schema = pd.read_csv("survey_results_schema.csv")

In [14]:
display(df_public,df1_schema)

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65432,65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65433,65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65436,65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,qid,qname,question,force_resp,type,selector
0,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
1,QID127,Age,What is your age?*,True,MC,SAVR
2,QID296,Employment,Which of the following best describes your cur...,True,MC,MAVR
3,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR
4,QID341,Check,Just checking to make sure you are paying atte...,True,MC,SAVR
...,...,...,...,...,...,...
82,QID337,JobSatPoints_7,"Learning and using new technology, including p...",NaN,MC,MAVR
83,QID337,JobSatPoints_8,"Designing and building environments, databases...",NaN,MC,MAVR
84,QID337,JobSatPoints_9,"Being a power user of a tool, developer langua...",NaN,MC,MAVR
85,QID337,JobSatPoints_10,Working with new and/or top-quality hardware,NaN,MC,MAVR
86,QID337,JobSatPoints_11,A well-staffed/sourced internal network that m...,NaN,MC,MAVR

In [18]:
df1_schema.head(10)

,qid,qname,question,force_resp,type,selector
0,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
1,QID127,Age,What is your age?*,True,MC,SAVR
2,QID296,Employment,Which of the following best describes your cur...,True,MC,MAVR
3,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR
4,QID341,Check,Just checking to make sure you are paying atte...,True,MC,SAVR
5,QID297,CodingActivities,Which of the following best describes the code...,False,MC,MAVR
6,QID25,EdLevel,Which of the following best describes the high...,True,MC,SAVR
7,QID276,LearnCode,How do you learn to code? Select all that apply.,False,MC,MAVR
8,QID281,LearnCodeOnline,What online resources do you use to learn to c...,False,MC,MAVR
9,QID331,TechDoc,What is the source of the technical documentat...,False,MC,MAVR

In [45]:
df_public.head(3)

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN

In [46]:
print(df_public.columns.tolist())

['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check', 'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline', 'TechDoc', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize', 'PurchaseInfluence', 'BuyNewTool', 'BuildvsBuy', 'TechEndorse', 'Country', 'Currency', 'CompTotal', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'LanguageAdmired', 'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'DatabaseAdmired', 'PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 'PlatformAdmired', 'WebframeHaveWorkedWith', 'WebframeWantToWorkWith', 'WebframeAdmired', 'EmbeddedHaveWorkedWith', 'EmbeddedWantToWorkWith', 'EmbeddedAdmired', 'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith', 'MiscTechAdmired', 'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith', 'ToolsTechAdmired', 'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'NEWCollabToolsAdmired', 'OpSysPersonal use', 'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith', 'OfficeStackAsyncAdmired', 'OfficeStackSyncHaveWorkedWith', 'OfficeStackSyncWantToWorkWith', 'OfficeStackSyncAdmired', 'AISearchDevHaveWorkedWith', 'AISearchDevWantToWorkWith', 'AISearchDevAdmired', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq', 'SOHow', 'SOComm', 'AISelect', 'AISent', 'AIBen', 'AIAcc', 'AIComplex', 'AIToolCurrently Using', 'AIToolInterested in Using', 'AIToolNot interested in Using', 'AINextMuch more integrated', 'AINextNo change', 'AINextMore integrated', 'AINextLess integrated', 'AINextMuch less integrated', 'AIThreat', 'AIEthics', 'AIChallenges', 'TBranch', 'ICorPM', 'WorkExp', 'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4', 'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Knowledge_8', 'Knowledge_9', 'Frequency_1', 'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering', 'Frustration', 'ProfessionalTech', 'ProfessionalCloud', 'ProfessionalQuestion', 'Industry', 'JobSatPoints_1', 'JobSatPoints_4', 'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase', 'ConvertedCompYearly', 'JobSat']

In [30]:
df1_schema.columns

Index(['qid', 'qname', 'question', 'force_resp', 'type', 'selector'], dtype='object')

In [31]:
df1_schema.head(10)

,qid,qname,question,force_resp,type,selector
0,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
1,QID127,Age,What is your age?*,True,MC,SAVR
2,QID296,Employment,Which of the following best describes your cur...,True,MC,MAVR
3,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR
4,QID341,Check,Just checking to make sure you are paying atte...,True,MC,SAVR
5,QID297,CodingActivities,Which of the following best describes the code...,False,MC,MAVR
6,QID25,EdLevel,Which of the following best describes the high...,True,MC,SAVR
7,QID276,LearnCode,How do you learn to code? Select all that apply.,False,MC,MAVR
8,QID281,LearnCodeOnline,What online resources do you use to learn to c...,False,MC,MAVR
9,QID331,TechDoc,What is the source of the technical documentat...,False,MC,MAVR

In [32]:
df_public.ResponseId.nunique() #1. Скільки респондентів пройшли опитування

65437

In [33]:
df_public.shape

(65437, 114)

In [42]:
question = set(df1_schema.qname.unique()) & set(df_public.columns)
df_public.dropna(subset=question).shape[0] # 2. Скільки респондентів відповіли на всі запитання

6306

In [47]:
df_public.WorkExp.mean()

11.46695663901814

In [50]:
print(f'Mean: {round(df_public.WorkExp.mean(),2)}') #3. Яке значення міри центральної тенденції для досвіду (WorkExp) респондентів
print(f'Mode: {round(df_public.WorkExp.mode(),2)}')
print(f'Median: {round(df_public.WorkExp.median(),2)}')

Mean: 11.47
Mode: 0    3.0
Name: WorkExp, dtype: float64
Median: 9.0

In [55]:
df_public[df_public.RemoteWork == 'Remote'].shape[0] 
#4. Скільки респондентів працює віддалено

65437

5. Який відсоток респондентів програмується на Pythonyton

In [56]:
df_public.LanguageHaveWorkedWith.str.contains('python', case=False, na=False)

0        False
1         True
2        False
3         True
4         True
         ...
65432    False
65433    False
65434    False
65435     True
65436     True
Name: LanguageHaveWorkedWith, Length: 65437, dtype: bool

user_python_persent=round(sum(df_public.LanguageHaveWorkedWith.str.contains('python', case=False, na=False)) / (df_public.ResponseId.nunique())*100, 2)
user_python_persent

In [62]:
sum(df_public.LanguageHaveWorkedWith.str.contains('python', case=False, na=False))

30795

6. Скільки респондентів навчалося програмувати за допомогою онлайн-курсів

In [68]:
sum(df_public.LearnCode.str.contains('online courses', case=False, na=False))

30271

In [69]:
df_public.LearnCode.str.contains('online courses', case=False, na=False)

0        False
1        False
2        False
3         True
4        False
         ...
65432    False
65433    False
65434    False
65435    False
65436    False
Name: LearnCode, Length: 65437, dtype: bool

7. Серед респондентів, які програмують на Python в групуванні по країнах, яка середня та медіанна сума компенсації (ConvertedCompYearly) в кожній країні?

In [72]:
df_python = df_public.LanguageHaveWorkedWith.str.contains('python', case=False, na=False)
df_python

0        False
1         True
2        False
3         True
4         True
         ...
65432    False
65433    False
65434    False
65435     True
65436     True
Name: LanguageHaveWorkedWith, Length: 65437, dtype: bool

In [73]:
df_ConvertedCompYearly = df[df_python == 1].dropna(subset='ConvertedCompYearly') \
                                            .groupby('Country', as_index=False) \
                                            .agg({'ConvertedCompYearly':['mean','median']})

In [74]:
df_ConvertedCompYearly

                                  Country ConvertedCompYearly
                                                         mean    median
0                             Afghanistan         4543.000000    4768.5
1                                 Albania        56295.000000   56295.0
2                                 Algeria         9053.285714    6230.0
3                                 Andorra       193331.000000  193331.0
4                                  Angola            6.000000       6.0
..                                    ...                 ...       ...
146  Venezuela, Bolivarian Republic of...        21500.000000    7100.0
147                              Viet Nam        14014.562500   10180.0
148                                 Yemen        10297.333333    5333.0
149                                Zambia        28123.666667   22803.0
150                              Zimbabwe        37500.000000   18000.0

[151 rows x 3 columns]

8. Які рівні освіти мають 5 респондентів з найбільшою компенсацією?

In [79]:
df_public[['ResponseId','EdLevel','ConvertedCompYearly']].sort_values(by='ConvertedCompYearly', ascending=False).reset_index(drop=True).head(5)

,ResponseId,EdLevel,ConvertedCompYearly
0,15838,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",16256603.0
1,12724,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",13818022.0
2,28380,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",9000000.0
3,17594,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",6340564.0
4,17673,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",4936778.0

1. У кожній віковій категорії, який відсоток респондентів програмується на Python?

In [98]:
df_python = df_public.LanguageHaveWorkedWith.str.contains('python', case=False, na=False)
df_python

0        False
1         True
2        False
3         True
4         True
         ...
65432    False
65433    False
65434    False
65435     True
65436     True
Name: LanguageHaveWorkedWith, Length: 65437, dtype: bool

In [99]:


# Створюємо маску для Python
df["Uses_Python"] = df["LanguageHaveWorkedWith"].str.contains("python", case=False, na=False)

# Рахуємо загальну кількість респондентів у кожній віковій категорії
age_counts = df.groupby("Age").size()

# Рахуємо, скільки з них працює з Python
python_counts = df.groupby("Age")["Uses_Python"].sum()

# Обчислюємо відсоток
df_python_percentage = (python_counts / age_counts * 100).reset_index(name="Python_Percentage")

# Виводимо результат
print(df_python_percentage)

                  Age  Python_Percentage
0     18-24 years old          55.922826
1     25-34 years old          45.773912
2     35-44 years old          41.520546
3     45-54 years old          41.910706
4     55-64 years old          40.427184
5   65 years or older          37.564767
6   Prefer not to say          45.341615
7  Under 18 years old          64.875389